"""empty message

Revision ID: 009bdd4f9e68
Revises: 828a5223032c
Create Date: 2023-06-20 13:24:14.924633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009bdd4f9e68'
down_revision = '828a5223032c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
